### ISSUE TITLE
Parameter `auth` is deprecated. Use `username` / `password` instead.

### ISSUE THREAD

**Issue by tehshane** [saintedlama/toggl-client#9]
Since the update to the latest version of `got` in 6c84412, I'm getting this error when I try to connect to the Toggl API.

```
(node:2384) UnhandledPromiseRejectionWarning: TypeError: Parameter `auth` is deprecated. Use `username` / `password` instead.
    at normalizeArguments (/home/REDACTED/node_modules/got/dist/source/core/index.js:430:19)
    at got (/home/REDACTED/node_modules/got/dist/source/create.js:112:39)
    at TogglClient.request (/home/REDACTED/node_modules/toggl-client/lib/client.js:66:30)
    at TogglClient.get (/home/REDACTED/node_modules/toggl-client/lib/client.js:49:23)
    at TimeEntries.list (/home/REDACTED/node_modules/toggl-client/lib/time-entries.js:21:30)
```

As the error suggests, looks like they deprecated the `auth` method in https://github.com/sindresorhus/got/pull/1051

I'll try and get a PR ready for it, but just a heads up.

Thanks! 😀

**Comment by saintedlama** [comment]
Fixed in 1.1.0
